# Generated by Django 5.0.6 on 2024-07-05 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_book_id_alter_chat_id_alter_deleterequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleterequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
